cragads/urls.py
from django.contrib import admin
from django.urls import path,include
from myapplist import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index,name='index'),
    path('', include('myapplist.urls'))
]

myapplist/urls.py
from django.urls import path
from . import views


app_name = 'myapplist'

urlpatterns = [
	# www.mywesite.com
	path('', views.base,name='base'),

	# www.mysite.com/new_search
	path('new_search', views.new_search,name='new_search'),

	# www.mysite.com/topic%20name
	path('query?=<str:query>/', views.index,name='index'),

	# www.mysite.com/topicc%20name/2
	path('<str:query>/', views.detail,name='detail'),

]

myapplist/models.py
from django.db import models

# Create your models here.
# python manage.py makemigrations myapplist
# python manage.py migrate
# python manage.py sqlmigrate myapplist 0001

class Search(models.Model):
	search_field = models.CharField(max_length=200)
	created = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name_plural = 'Searches'

	def __str__(self):
		return self.search_field

myapplist/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect,Http404
from django.utils import timezone
from  bs4 import BeautifulSoup
import requests
from requests.compat import quote_plus
from .models import Search
import re
space_remover = re.compile('\s+')


def base(request):
	return render(request, 'myapplist/base.html')


def new_search(request)	:
	search=request.POST.get('search')
	if search=='':
		return HttpResponseRedirect(reverse('myapplist:base'))
		

	Search.objects.create(search_field=search)

	return HttpResponseRedirect(reverse('myapplist:index',args=(search,) )) 


def index(request,query):
	url = f'https://mumbai.craigslist.org/search/?query={ quote_plus(query) }'
	response = requests.get(url)

	img_url = 'https://images.craigslist.org/{}_300x300.jpg'

	soup = BeautifulSoup(response.text,features='html.parser')
	
	topics=[]
	for topic in soup.find_all('li',{'class':'result-row'}):
		title = topic.find('a',{'class':'result-title'}).get_text()
		l = topic.find('a',{'class':'result-title'}).get('href').split('/')
		link = l[2].split('.')[0]+'+'+ l[3]+'+'+l[5]+'+'+l[6].split('.')[0]

		if topic.find('a',{'class':'result-image'}).get('data-ids'):
			imgid = topic.find('a',{'class':'result-image'}).get('data-ids').split(',')[0].split(':')[1]
			img = img_url.format(imgid)
		else :
			img = 'https://craigslist.org/images/peace.jpg'
		topics.append((title,link,img))

	context = {
		'search':query,
		'topics':topics,
	}
	return render(request, 'myapplist/index.html',context)


def detail(request,query):
	query =query.split('+')
	url = 'https://{}.craigslist.org/{}/d/{}/{}.html'.format(query[0],query[1],query[2],query[3])

	response = requests.get(url)
	soup = BeautifulSoup(response.text,features='html.parser')

	title = soup.find('h2',{'class':'postingtitle'}).get_text()
	title = space_remover.sub(" ",title)

	date = soup.find('p',{'id':'display-date'}).get_text()
	date = space_remover.sub(" ",date)

	body_text = soup.find('section',{'id':'postingbody'}).get_text()[30:]
	body_text = re.sub(r'(https?://\S+)', r'<a href="\1" target="blank">\1</a>', body_text)

	notices = [t.get_text() for t in soup.find('ul',{'class':'notices'}).find_all('li')]


	imgsrc = None
	if soup.find('div',{'class':'gallery'}):
		imgsrc = soup.find('div',{'class':'gallery'}).find('img').get('src')
		
	context = {
		'title':title,
		'date':date,
		'body_text':body_text,
		'imgsrc':imgsrc,
		'notices':notices,
	}

	return render(request, 'myapplist/detail.html',context=context)

myapplist/templates/myapplist/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>cragads</title>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" type="text/css" href="{% static 'myapplist/css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <script src="https://kit.fontawesome.com/8806ff8ba0.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

    <script>
      <!-- this part is important! -->
      $(document).ready(function () {
        $(".button-collapse").sideNav();
      });
    </script>
</head>


<body>


	<nav class="blue">
		<div class="container nav-wrapper" >
        	<a href=" {% url 'myapplist:base' %} " class="brand-logo">cragads</a>
        	<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
	        <ul class="right hide-on-med-and-down ">
	            <li><a href="">Home</a></li>
	            <li><a href="https://www.linkedin.com/in/abhishek-vaish-b3195817a/" ><i class="fab fa-linkedin-in"></i></a></li>
	            <li><a href="https://github.com/Abhishekvaish"><i class="fab fa-github"></i></a></li>
	            <li><a href="https://twitter.com/Abhishekvaish40"><i class="fab fa-twitter"></i></a></li>
	        </ul>
	    </div>
	</nav>
	<ul class="side-nav" id="mobile-demo">
		<li><a href="">Home</a></li>
        <li><a href="https://www.linkedin.com/in/abhishek-vaish-b3195817a/" ><i class="fab fa-linkedin-in"></i> LinkedIn</a></li>
        <li><a href="https://github.com/Abhishekvaish"><i class="fab fa-github"></i> Github</a></li>
        <li><a href="https://twitter.com/Abhishekvaish40"><i class="fab fa-twitter"></i> twitter</a>
	</ul>

	

	<div class="container">
		{% block search %}

	    <h2 style="text-align: center">What do you want to search for on cragads List?</h2>
	    <br/><br/>
	    <form action="{% url 'myapplist:new_search'  %}" method="post" class="center">
			{% csrf_token  %}
			<input type="text" name="search" placeholder="search craglist for job, course, products etc" >
			<br/><br/>
			<button class="btn waves-effect waves-light " type="submit" name="action">
				Search<i class="material-icons right" >search</i>
			</button>
		</form>
		<br/><br/><br/><br/>

	    <div class="row">
	        <div class="col s4 center">
	            <!-- Promo Content 1 goes here -->
	                <i class="large material-icons" style="color: #EE6E73">flash_on</i>
	                <p>Fast craigslist web scraper</p>
	                <p class="light center">Scrape away right here with a beautiful GUI.</p>
	        </div>

	        <div class="col s4 center">
	            <!-- Promo Content 2 goes here -->
	                <i class="large material-icons" style="color: orange">camera</i>
	                <p>User friendly </p>
	                <p class="light center">Very Simple and easy to use .</p>
	        </div>

	        <div class="col s4 center">
	            <!-- Promo Content 3 goes here -->
	                <i class="large material-icons" style="color: blue">chrome_reader_mode</i>
	                <p>A much cooler front-end to Craigslist</p>
	                <p class="light center">We built this with ❤️</p>
	        </div>
	    </div>

	    {% endblock %}


	    {% block content %}

	    {% endblock content %}
	</div>

	<footer class="page-footer blue">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Cragads</h5>
                <p class="grey-text text-lighten-4">A fast craigslist web scraper with a nice front-end..</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Contact</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="https://mail.google.com/mail/u/0/?view=cm&fs=1&to=abhishek953566936222@gmail.com&tf=1">abhishek953566936222@gmail.com</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2020 Copyright Text
             <a class="grey-text text-lighten-4 right" href="#!">This website is made with Django</a>
            </div>
          </div>
    </footer>

</body>


</html>

myapplist/templates/myapplist/detail.html
{% extends 'myapplist/base.html' %}

{% block search %}
	<br/><br/><br/>
	<form action="{% url 'myapplist:new_search'  %}" method="post" class="row center">
			{% csrf_token  %}
			<input type="text" name="search" placeholder="search craglist for anything " class="col s10" >
			
			<button class="btn waves-effect waves-light col s2" type="submit" name="action">
				Search<i class="material-icons right" >search</i>
			</button>
	</form>	
{% endblock	 %}

{% block content %}
<br/>
<br/>
<div>
	<h2 style="font-family: Georgia, Times, 'Times New Roman', serif;" >{{title|title}}</h2>	
</div>
<div class="row">
	<p class="georgia">
		{% if imgsrc %}
		<img src="{{imgsrc}}" align="left"  style="padding-right: 40px;" width="500" /> 
		{% endif %}
		{% autoescape off %}
		{{body_text}} 
		{% endautoescape %}
	</p>
	<ul type="disc">	
		{% for n in notices %}
		 <li style="font-family: Georgia, Times, 'Times New Roman', serif;" > {{n}}</li>
		{% endfor %}
	</ul>
</div>


<br/>
<p align="right"  >{{date}}</p>
<br/>




{% endblock %}

myapplist/templates/myapplist/index.html
{% extends 'myapplist/base.html' %}

{% block search %}
	<br/><br/><br/>
	<form action="{% url 'myapplist:new_search'  %}" method="post" class="row center">
			{% csrf_token  %}
			<input type="text" name="search" placeholder="search craglist for anything " class="col s10" >
			
			<button class="btn waves-effect waves-light col s2" type="submit" name="action">
				Search<i class="material-icons right" >search</i>
			</button>
	</form>	
{% endblock	 %}



{% block content %}

<h2 class="center">{{search|title}}</h2>

<div class="row">
	{% for topic in topics %}
	<div class="col s12 m4 l4">
		<div class="card">
	        <div class="card-image">
	          <img src="{{topic.2}}">
	        </div>
	        <div class="card-content">
	          <p>{{topic.0}}</p>
	        </div>
	        <div class="card-action">
	          <a href="{% url 'myapplist:detail' topic.1 %}">View Full article</a>
	        </div>
		</div>
	</div>
	{% endfor %}

</div>

{% endblock %}